-- Set all Supabase role passwords (generated by Aspire)
-- Uses psql variable substitution like the official roles.sql
ALTER USER authenticator WITH PASSWORD 'local-dev-password-123';
ALTER USER supabase_auth_admin WITH PASSWORD 'local-dev-password-123';
ALTER USER supabase_storage_admin WITH PASSWORD 'local-dev-password-123';
ALTER USER supabase_admin WITH PASSWORD 'local-dev-password-123';
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pgbouncer') THEN
    EXECUTE format('ALTER USER pgbouncer WITH PASSWORD %L', 'local-dev-password-123');
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'supabase_functions_admin') THEN
    EXECUTE format('ALTER USER supabase_functions_admin WITH PASSWORD %L', 'local-dev-password-123');
  END IF;
END $$;