using RunXcTiming.AppHost;
using Nextended.Aspire;
using Nextended.Aspire.Hosting.Supabase.Builders;

// =============================================================================
//  RunXcTiming — .NET Aspire AppHost
//  Generated by aspire.love. Run with `aspire run` (or F5 in your IDE).
//  Mode: FullLocal — runs the full Supabase stack locally in Docker.
//  Edit Constants.cs for project-specific values.
// =============================================================================

var builder = DistributedApplication.CreateBuilder(args);

// When publishing (e.g. `azd up`) provision an Azure Container Apps environment
// as the deployment target. Has no effect during local development.
if (builder.ExecutionContext.IsPublishMode)
{
    builder.AddAzureContainerAppEnvironment("azure-container-env")
        .WithAzdResourceNaming();
}

// Paths to the Lovable project's Supabase assets (two levels up from the AppHost).
var supabasePath = Path.GetFullPath(Path.Combine(builder.AppHostDirectory, "..", "..", "supabase"));
var migrationsPath = Path.Combine(supabasePath, "migrations");
var edgeFunctionsPath = Path.Combine(supabasePath, "functions");

// -----------------------------------------------------------------------------
//  Supabase — the full stack (Postgres, Auth, Storage, Realtime, Kong, Studio)
//  runs locally in Docker, orchestrated by Aspire.
// -----------------------------------------------------------------------------
var supabase = builder.AddSupabase("runxctiming-supabase")
    .ConfigureDatabase(db => db
        .WithPassword("local-dev-password-123"))
    .ConfigureStudio(studio => studio
        .WithProjectName("RunXcTiming")
        .WithOrganizationName("My Company")
        .WithExternalHttpEndpoints()
        .WithLogin(Constants.User.Default.Name, Constants.User.Default.Password))
    .WithRegisteredUser(Constants.User.Default.Email, Constants.User.Default.Password, Constants.User.Default.Name)
    // Full Local: apply this project's migrations and serve its edge functions.
    // To switch to Sync mode later, replace the two lines below with:
    //     .WithProjectSync(Constants.Supabase.SyncInfo)
    .WithMigrations(migrationsPath)
    .WithEdgeFunctions(edgeFunctionsPath)
    .ConfigureEdgeRuntime(runtime =>
    {
        runtime.WithEnvironment("DENO_REGION", "eu-central-1");
    })
    .WithClearCommand();

// -----------------------------------------------------------------------------
//  Frontend — the Lovable Vite app. The `aspire` npm script (npm i && npm run dev)
//  is launched by Aspire and pointed at the local Supabase stack above.
// -----------------------------------------------------------------------------
var frontend = builder.AddJavaScriptApp("runxctiming-frontend", "../..", "aspire")
    .WithHttpEndpoint(targetPort: builder.ExecutionContext.IsPublishMode ? 80 : 8080, name: "http")
    .WithExternalHttpEndpoints()
    .WithSupabaseVite(supabase)
    .PublishAsDockerFile()
    .WaitFor(supabase);

// Point Supabase auth redirects at the frontend (works locally and when deployed).
supabase.ConfigureAuth(auth => auth.WithSiteUrl(frontend));

builder
    .Build()
    .EnsureDockerRunningIfLocalDebug()
    .Run();
